# Generated by Django 5.2.4 on 2025-07-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='العمر')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الطول (سم)')),
                ('diabetes_type', models.CharField(choices=[('Type 1', 'النوع الأول'), ('Type 2', 'النوع الثاني'), ('Gestational', 'سكري الحمل'), ('Other', 'أخرى')], default='Type 2', max_length=20, verbose_name='نوع السكري')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التشخيص')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف تعريف المريض',
                'verbose_name_plural': 'ملفات تعريف المرضى',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدواء')),
                ('dosage', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجرعة')),
                ('administration_method', models.CharField(choices=[('Oral', 'فموي'), ('Injection', 'حقن'), ('Topical', 'موضعي'), ('Other', 'أخرى')], default='Oral', max_length=20, verbose_name='طريقة الاستخدام')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.patientprofile', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
            },
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='نص الملاحظة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الطبيب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='core.patientprofile', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'ملاحظة طبيب',
                'verbose_name_plural': 'ملاحظات الأطباء',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BloodGlucoseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='قيمة السكر')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('reading_type', models.CharField(choices=[('Before Meal', 'قبل الوجبة'), ('After Meal', 'بعد الوجبة'), ('Fasting', 'صائم'), ('Before Sleep', 'قبل النوم'), ('Other', 'أخرى')], default='Other', max_length=20, verbose_name='نوع القياس')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_readings', to='core.patientprofile', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'قراءة سكر',
                'verbose_name_plural': 'قراءات السكر',
                'ordering': ['-timestamp'],
            },
        ),
    ]
