# Generated by Django 5.2.4 on 2025-08-14 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodglucosereading',
            name='reading_type',
            field=models.CharField(choices=[('Fasting', 'صائم'), ('After Meal', 'بعد الأكل'), ('Random', 'عشوائي')], default='Random', max_length=20, verbose_name='نوع القراءة'),
        ),
        migrations.AlterField(
            model_name='bloodglucosereading',
            name='reading_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
