# Generated by Django 5.2.4 on 2025-08-14 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bloodglucosereading_reading_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['alert_date', 'alert_time'], 'verbose_name': 'تنبيه', 'verbose_name_plural': 'التنبيهات'},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='related_reading',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='sender_user',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 14, 2, 33, 141880, tzinfo=datetime.timezone.utc), verbose_name='تاريخ التنبيه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_time',
            field=models.TimeField(default='12:00', verbose_name='وقت التنبيه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 14, 14, 4, 49, 451816, tzinfo=datetime.timezone.utc), verbose_name='وقت الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 8, 14, 14, 5, 4, 323843, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='اسم التنبيه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='recurrence',
            field=models.CharField(choices=[('Once', 'مرة واحدة'), ('Daily', 'يومياً'), ('Weekly', 'أسبوعياً')], default='Once', max_length=10, verbose_name='التكرار'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Medication', 'تذكير دواء'), ('Measurement', 'تذكير قياس'), ('General', 'تذكير عام')], default='General', max_length=20, verbose_name='نوع التنبيه'),
        ),
    ]
