# Generated by Django 5.2.4 on 2025-07-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientprofile_address_patientprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='medical_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات طبية للطبيب'),
        ),
    ]
