# Generated by Django 5.2.4 on 2025-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='core.patientprofile'),
        ),
    ]
