# Generated by Django 5.2.4 on 2025-07-31 13:10

import core.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bloodglucosereading',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctornote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='bloodglucosereading',
            name='reading_type',
        ),
        migrations.RemoveField(
            model_name='bloodglucosereading',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='bloodglucosereading',
            name='value',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='administration_method',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='bloodglucosereading',
            name='reading_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 31, 13, 8, 13, 968275, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodglucosereading',
            name='reading_value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=core.models.attachment_file_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.patientprofile'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bloodglucosereading',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodglucosereading',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_readings', to='core.patientprofile'),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_written_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='note_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='core.patientprofile'),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.patientprofile'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='diabetes_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.patient_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField()),
                ('consultation_time', models.TimeField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-consultation_date', '-consultation_time'],
            },
        ),
    ]
