# Generated by Django 5.2.4 on 2025-08-04 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نص التنبيه')),
                ('alert_type', models.CharField(choices=[('High Sugar', 'ارتفاع السكر'), ('Low Sugar', 'انخفاض السكر'), ('Missed Medication', 'جرعة دواء مفقودة'), ('Appointment Reminder', 'تذكير موعد'), ('General', 'عام'), ('Doctor Note', 'ملاحظة طبيب جديدة')], default='General', max_length=50, verbose_name='نوع التنبيه')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التنبيه')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.patientprofile', verbose_name='المريض')),
                ('related_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bloodglucosereading', verbose_name='قراءة السكر المرتبطة')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'تنبيه / إشعار',
                'verbose_name_plural': 'التنبيهات / الإشعارات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
