# Generated by Django 5.2.4 on 2025-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctorprofile_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Confirmed', 'مقبول'), ('Rejected', 'مرفوض')], default='Pending', max_length=10),
        ),
    ]
