# Generated by Django 5.2.4 on 2025-08-05 11:34

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255, verbose_name='التخصص')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة عن الطبيب')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=core.models.doctor_profile_picture_path, verbose_name='صورة الطبيب')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط التقييم')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح الآن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_patients', to='core.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_doctors', to='core.patientprofile')),
            ],
            options={
                'verbose_name': 'طبيب مفضل',
                'verbose_name_plural': 'الأطباء المفضلون',
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
